//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Welding
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailAssemblyType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetailAssemblyType()
        {
            this.DetailPartTypes = new HashSet<DetailPartType>();
            this.WeldingAssemblyInstructions = new HashSet<WeldingAssemblyInstruction>();
            this.WeldingAssemblyControls = new HashSet<WeldingAssemblyControl>();
            this.DetailAssemblies = new HashSet<DetailAssembly>();
        }
    
        public int ID { get; set; }
        public int Status { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Name { get; set; }
        public string Label { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> Image { get; set; }
        public Nullable<System.Guid> SchemeImage { get; set; }
        public Nullable<System.Guid> SpecsImage { get; set; }
        public Nullable<System.Guid> RouteImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailPartType> DetailPartTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeldingAssemblyInstruction> WeldingAssemblyInstructions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeldingAssemblyControl> WeldingAssemblyControls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailAssembly> DetailAssemblies { get; set; }
    }
}
