//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Welding
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public System.Guid GUID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> AddedUserID { get; set; }
        public string Subfolder { get; set; }
        public string ContentType { get; set; }
        public string Filename { get; set; }
        public Nullable<long> Length { get; set; }
        public Nullable<int> ImageWidth { get; set; }
        public Nullable<int> ImageHeight { get; set; }
    }
}
