//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Welding
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibraryDocument
    {
        public int ID { get; set; }
        public int Status { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> UserAccountID { get; set; }
        public System.Guid Document { get; set; }
        public string OriginalFilename { get; set; }
        public string GroupName { get; set; }
    }
}
