//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Welding
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance
    {
        public int ID { get; set; }
        public int WeldingMachineID { get; set; }
        public int Status { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateFinished { get; set; }
        public int CreatedUserID { get; set; }
        public Nullable<int> ResponsibleUserID { get; set; }
        public int MaintenanceStatus { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> Photo { get; set; }
        public Nullable<long> TotalTimeSec { get; set; }
        public Nullable<long> TimeSinceLastServiceSec { get; set; }
    
        public virtual WeldingMachine WeldingMachine { get; set; }
    }
}
