//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Welding
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetworkDevice
    {
        public int ID { get; set; }
        public int OrganizationUnitID { get; set; }
        public int Status { get; set; }
        public string Name { get; set; }
        public string Model { get; set; }
        public string MAC { get; set; }
        public string IP { get; set; }
        public string Port { get; set; }
        public string InventoryNumber { get; set; }
        public string DeviceLogin { get; set; }
        public string DevicePassword { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<double> PlanPositionX { get; set; }
        public Nullable<double> PlanPositionY { get; set; }
    
        public virtual OrganizationUnit OrganizationUnit { get; set; }
    }
}
