//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Welding
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int ID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int Status { get; set; }
        public int UserAccountID { get; set; }
        public string Type { get; set; }
        public string Key { get; set; }
        public string JSON { get; set; }
        public bool Read { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
