//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Welding
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organization()
        {
            this.OrganizationUnits = new HashSet<OrganizationUnit>();
        }
    
        public int ID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Name { get; set; }
        public int Status { get; set; }
        public string FullName { get; set; }
        public string Scope { get; set; }
        public string Description { get; set; }
        public Nullable<int> HeadUserId { get; set; }
        public Nullable<System.Guid> Logo { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Phones { get; set; }
        public string Address { get; set; }
        public string INN { get; set; }
        public string OGRN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganizationUnit> OrganizationUnits { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
