//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Welding
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameter
    {
        public int ID { get; set; }
        public int MeasureUnitID { get; set; }
        public string PropertyCode { get; set; }
        public string Type { get; set; }
    
        public virtual MeasureUnit MeasureUnit { get; set; }
    }
}
