//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Welding
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueueTask
    {
        public int ID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int Status { get; set; }
        public Nullable<int> UserAccountID { get; set; }
        public Nullable<System.DateTime> DateStarted { get; set; }
        public Nullable<System.DateTime> DateFinished { get; set; }
        public Nullable<System.DateTime> ScheduledOn { get; set; }
        public string TaskName { get; set; }
        public string TaskParametersJSON { get; set; }
        public Nullable<int> StatusResult { get; set; }
        public string StatusMessage { get; set; }
        public Nullable<int> Priority { get; set; }
        public string TaskResultJSON { get; set; }
    }
}
