//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Welding
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyPass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SurveyPass()
        {
            this.SurveyPassQuestionAnswers = new HashSet<SurveyPassQuestionAnswer>();
        }
    
        public int ID { get; set; }
        public int SurveyID { get; set; }
        public int UserID { get; set; }
    
        public virtual Survey Survey { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveyPassQuestionAnswer> SurveyPassQuestionAnswers { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
