//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Welding
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translation
    {
        public int ID { get; set; }
        public string Lang { get; set; }
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public string IDName { get; set; }
        public string IDValue { get; set; }
        public string Value { get; set; }
    }
}
