//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Welding
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRolePermission
    {
        public int UserRoleID { get; set; }
        public int UserPermissionID { get; set; }
        public Nullable<bool> Read { get; set; }
        public Nullable<bool> Write { get; set; }
    
        public virtual UserPermission UserPermission { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
