//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Welding
{
    using System;
    using System.Collections.Generic;
    
    public partial class vStatePropValue
    {
        public int ID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int WeldingMachineID { get; set; }
        public Nullable<int> WeldingMachineStatus { get; set; }
        public int StateDurationMs { get; set; }
        public string PropertyCode { get; set; }
        public string PropertyType { get; set; }
        public string Value { get; set; }
    }
}
