//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Welding
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeldingAssemblyControl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WeldingAssemblyControl()
        {
            this.WeldingAssemblyControlResults = new HashSet<WeldingAssemblyControlResult>();
        }
    
        public int ID { get; set; }
        public int WeldingDetailAssemblyTypeID { get; set; }
        public int Status { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> CreatedUserID { get; set; }
        public Nullable<int> DeveloperUserID { get; set; }
        public string DeveloperName { get; set; }
        public bool DeveloperSigned { get; set; }
        public Nullable<System.DateTime> DeveloperSignedOn { get; set; }
        public Nullable<int> ApproverUserID { get; set; }
        public string ApproverName { get; set; }
        public bool ApproverSigned { get; set; }
        public Nullable<System.DateTime> ApproverSignedOn { get; set; }
        public string JSON { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedUserID { get; set; }
    
        public virtual DetailAssemblyType DetailAssemblyType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeldingAssemblyControlResult> WeldingAssemblyControlResults { get; set; }
    }
}
