//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Welding
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeldingLimitProgramParameter
    {
        public int ID { get; set; }
        public string PropertyCode { get; set; }
        public int WeldingLimitProgramID { get; set; }
        public string Value { get; set; }
        public string MinValue { get; set; }
        public string MaxValue { get; set; }
    
        public virtual WeldingLimitProgram WeldingLimitProgram { get; set; }
    }
}
