//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Welding
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeldingMachineState
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WeldingMachineState()
        {
            this.WeldingMachineParameterValues = new HashSet<WeldingMachineParameterValue>();
        }
    
        public int ID { get; set; }
        public int WeldingMachineID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public Nullable<int> WeldingMachineStatus { get; set; }
        public string RFID { get; set; }
        public string Control { get; set; }
        public Nullable<int> ControlStatus { get; set; }
        public string ControlState { get; set; }
        public int StateDurationMs { get; set; }
        public string ErrorCode { get; set; }
        public Nullable<int> WeldingMaterialID { get; set; }
        public Nullable<bool> LimitsExceeded { get; set; }
        public Nullable<int> WeldingLimitProgramID { get; set; }
        public string WeldingLimitProgramName { get; set; }
    
        public virtual WeldingMachine WeldingMachine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeldingMachineParameterValue> WeldingMachineParameterValues { get; set; }
    }
}
