//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Welding
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeldingDetailAssemblyTaskState
    {
        public int ID { get; set; }
        public int TaskID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> CreatedUserID { get; set; }
        public string CreatedUserName { get; set; }
        public Nullable<int> TaskStatus { get; set; }
        public string Comments { get; set; }
    
        public virtual WeldingDetailAssemblyTask WeldingDetailAssemblyTask { get; set; }
    }
}
