//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Welding
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeldingAssemblyControlResult
    {
        public int ID { get; set; }
        public int WeldingAssemblyControlID { get; set; }
        public int DetailAssemblyID { get; set; }
        public int Status { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CreatedUserID { get; set; }
        public Nullable<int> ControllerUserID { get; set; }
        public string ControllerName { get; set; }
        public bool ControllerSigned { get; set; }
        public Nullable<System.DateTime> ControllerSignedOn { get; set; }
        public Nullable<int> HeadUserID { get; set; }
        public string HeadName { get; set; }
        public bool HeadSigned { get; set; }
        public Nullable<System.DateTime> HeadSignedOn { get; set; }
        public string JSON { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedUserID { get; set; }
    
        public virtual WeldingAssemblyControl WeldingAssemblyControl { get; set; }
        public virtual DetailAssembly DetailAssembly { get; set; }
    }
}
