//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Welding
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeldingLimitProgramHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WeldingLimitProgramHistory()
        {
            this.WeldingLimitProgramHistoryParameters = new HashSet<WeldingLimitProgramHistoryParameter>();
        }
    
        public int ID { get; set; }
        public int Status { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Name { get; set; }
        public int CreatedUserID { get; set; }
        public Nullable<int> WeldingMachineID { get; set; }
        public Nullable<int> WeldingMachineTypeID { get; set; }
        public bool IsMachineDefault { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeldingLimitProgramHistoryParameter> WeldingLimitProgramHistoryParameters { get; set; }
    }
}
