//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Welding
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeldingLimitProgram
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WeldingLimitProgram()
        {
            this.WeldingLimitProgramParameters = new HashSet<WeldingLimitProgramParameter>();
            this.WeldingLimitProgramSchedules = new HashSet<WeldingLimitProgramSchedule>();
        }
    
        public int ID { get; set; }
        public int Status { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Name { get; set; }
        public int CreatedUserID { get; set; }
        public Nullable<int> UpdatedUserID { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<int> WeldingMachineID { get; set; }
        public Nullable<int> WeldingMachineTypeID { get; set; }
        public bool IsMachineDefault { get; set; }
        public Nullable<int> UserAccountID { get; set; }
        public Nullable<int> UserRoleID { get; set; }
        public int ProgramStatus { get; set; }
        public Nullable<int> WeldingMaterialID { get; set; }
        public Nullable<bool> ByBarcode { get; set; }
        public string Barcode { get; set; }
    
        public virtual UserRole UserRole { get; set; }
        public virtual WeldingMachine WeldingMachine { get; set; }
        public virtual WeldingMachineType WeldingMachineType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeldingLimitProgramParameter> WeldingLimitProgramParameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeldingLimitProgramSchedule> WeldingLimitProgramSchedules { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
