//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Welding
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeldingDetailAssemblyTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WeldingDetailAssemblyTask()
        {
            this.WeldingDetailAssemblyTaskStates = new HashSet<WeldingDetailAssemblyTaskState>();
        }
    
        public int ID { get; set; }
        public Nullable<int> DetailAssemblyID { get; set; }
        public int Status { get; set; }
        public Nullable<int> TaskStatus { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> CreatedUserID { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> WorkerUserID { get; set; }
        public Nullable<int> ControllerUserID { get; set; }
        public Nullable<int> WeldingMachineID { get; set; }
        public string WeldingNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeldingDetailAssemblyTaskState> WeldingDetailAssemblyTaskStates { get; set; }
        public virtual DetailAssembly DetailAssembly { get; set; }
    }
}
