//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Welding
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeldingMachineType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WeldingMachineType()
        {
            this.WeldingLimitPrograms = new HashSet<WeldingLimitProgram>();
            this.WeldingMachines = new HashSet<WeldingMachine>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string ConfigurationJSON { get; set; }
        public Nullable<System.Guid> Photo { get; set; }
        public Nullable<System.Guid> PanelPhoto { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeldingLimitProgram> WeldingLimitPrograms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeldingMachine> WeldingMachines { get; set; }
    }
}
